site_name: dot-map

theme:
  name: material

nav:
  - "User Guide": index.md
  - "Changelog": changelog.md

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.details
  - attr_list

repo_url: https://github.com/Vopaaz/dot-map
repo_name: Vopaaz/dot-map
